config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :users
  get 'errors/not_found'
  get 'home/index'
  get 'index', to:'home#index'
  get 'home/not_available'
  get 'home/about'

  
  match "/404", to: "errors#not_found", via: :all # error handling
  match "/500", to: "errors#internal_server_error", via: :all # to change
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :user_id)
    end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    get_comments
  end

  def not_available
  end

  private
  def get_comments
    @comments = Comment.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :imageUrl)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <div class="reviewsname">    <%= image_tag "pics/av_default.png", class:"inline", alt: "pics/av_default.png" %> <!--@comment.user.imageUrl, onerror: 'this.error=null;this.src="pics/av_f_bolajuzon.png"'-->
<h6 >
    <%= comment.user.first_name %>
    <%= comment.user.last_name %>
    <button class="btn btn-grey">
      <%= link_to "Edit", edit_comment_path(comment) %>
    </button>
  </h6></div>
  <p>
    <%= comment.body %>
  </p>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment, class: "contents") do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.text_field :body, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "btn-primary", style:"line-height: 1.2;" %>
  </div>

  <div class="inline" >
    <%= link_to 'Back to comments', comments_path, class: "btn-secondary", style:"line-height: 1.2;" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing comment</h1>

  <%= render "form", comment: @comment %>

  <%= link_to "Show this comment", @comment, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to comments", comments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/comments/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Comments</h1>
    <%= link_to 'New comment', new_comment_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="comments" class="min-w-full">
    <%= render @comments %>
  </div>
</div>

app/views/comments/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New comment</h1>

  <%= render "form", comment: @comment %>
</div>

app/views/comments/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @comment %>

    <%= link_to 'Edit this comment', edit_comment_path(@comment), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this comment', comment_path(@comment), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to comments', comments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/home/_comment_section.html.erb
<aside style="height: 70vh; border-radius: 10px; margin-top: 20px;"> 
<!--    <div> <div class="reviewsname"><img src="static/img/pics/av_v_leit.png" alt=""><h6 >Victoria Leit</h6></div><p>Les recomiendo al profe mas datero del condado!</p></div>
    <div> <div class="reviewsname"><img src="static/img/pics/av_j_amar.png" alt=""><h6 >Juan Ignacio Amar</h6></div><p>Un maestro de los sintes! El mejor profe de audio</p></div>
    <div> <div class="reviewsname"><img src="static/img/pics/av_j_palmares.png" alt=""><h6 >Jesús Palmares</h6></div><p>Necesitas unas clases profesionales de producción? Toda la buena onda y el conocimiento en Anfibio.Clases</p></div>
    <div> <div class="reviewsname"><img src="static/img/pics/av_m_perez.png" alt=""><h6 >Marianela Pérez Salerno</h6></div><p>Anfibio son las clases espectalares de Mauricio Heller. Uso y recomiendo, aprendo a escuchar, mezclar y grabar con este simpático sujeto, que es tan amorosx como excelente docente</p></div>
    
-->
 <%= render @comments%>
 <div><%= link_to "Deja tu comentario", new_comment_path, class:'nav-link pl-6 text-gray-500'%></div>
</aside>

app/views/home/_footer.html.erb
<footer>
    <div class="text-s">Mauricio Heller 2022 // Ejemplo de Ruby on Rails</div>
</footer>

app/views/home/_header.html.erb
<header>    
    <div class="titlebar">
        <a href="/home/index.html">
            <%= image_tag "general/logo_navbar.svg", class: "logo"%>
        </a>
    </div>   
    <nav class="navbar" style="margin-top: 2pt;">
        <ul>
            <li>
                <%= link_to home_index_path do %>
                    <div class="text-amber-200">Intro</div></a> 
                <% end %>
            
            <li>
                <%= link_to home_not_available_path, class: 'w-full h-full' do %>
                    <div class="nav-link text-zinc-500">Cursos</div>
                <% end %>
                
            <li>
                <%= link_to home_about_path , class:'nav-link text-zinc-500' do %>
                    <div>Novedades</div>
                <% end %>
            <li>
                <%= link_to home_about_path , class:'nav-link text-amber-200' do %>
                    <div>Info</div>
                <% end %>
            <li>
                <%= link_to new_user_path , class:'nav-link text-amber-200' do %>
                    <div>Registrate</div>
                <% end %>
        </ul>    
    </nav>
</header>

app/views/home/about.html.erb
<main>
    <article style="flex: 1; overflow-y: unset;"> 
        <h1>Sobre Anfibio</h1>
        <h3 style="font-size:medium">Proximamente...</h3>
    </article>
</main>

app/views/home/index.html.erb
<main>
<article> 
    <h1 class="text-2xl">Hola!</h1>
    <h2 class="text-2xl">Tenemos algo para tí</h2>
    <div class="container flex justify-center"><%= image_tag "general/rana.svg", class: "centerimg ", style: "height: 300px;"%></div>
    <h3 class="title text-2xl">En anfibio creemos que la música<br>nace de la unión entre el alma y el instrumento,<br>entre el humano y la máquina</h3>
    <br>
    <h3 class="subtitle text-xl">nuestro plan de estudios que te ayudará a entender profundamente las tecnologías musicales de hoy y a integrar herramientas digitales como parte de tu paleta sonora</h3>
</article>
    <%= render 'home/comment_section'%>
</main>

app/views/home/not_available.html.erb
<main>
    <article style="flex: 1; overflow-y: unset;"> 
        <h2 style="font-size:x-large">This service is not available yet</h2>
        <h3 style="font-size:large">We are working on it</h3>
        <div class="flex justify-center"><%= image_tag "general/misc/workinprogress.svg", class:"centerimg", style:"height: 650px; margin-top: -50px; margin-bottom: -50px;"%></div>            
    </article>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Anfibio</title>
    <meta charset="UTF-8">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "styles", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application" %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;400;800&display=swap" rel="stylesheet"> 
	<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&family=Montserrat:wght@100;200;400;800&display=swap" rel="stylesheet"> 

</head>
<body>
    <%= render 'home/header'%>
    <%= yield %>
    <%= render 'home/footer'%>
</body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  


  <div>
    <%= form.label :first_name,style: "display: block" %>
    <%= form.text_field :first_name, :placeholder => 'First Name', class:"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>  
  <div>
    <%= form.label :last_name, class:"mt-5", style: "display: block" %>
    <%= form.text_field :last_name, :placeholder => 'Last Name', class:"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div>
    <%= form.label :email, class:"mt-5", style: "display: block" %>
    <%= form.text_field :email, :placeholder => 'example@email.com', class:"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div>
    <%= form.label :imageUrl, class:"mt-5", style: "display: block" %>
    <%= form.text_field :imageUrl, :placeholder => 'Paste image URL', class:"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="btn-primary mb-5">
    <%= form.submit %>
  </div>

  <div class="">
  <%= link_to "Back to users", users_path, class:"btn-secondary" %>
</div>


<% end %>
</div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">

  <p>
    <strong>imageUrl:</strong>
    <%= user.imageUrl %>
  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<div class="flex container items-center justify-center py-12 px-4 sm:px-6 lg:px-12">
<%= render "form", user: @user %>
</div>

<br>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>